---
- hosts: routers
  connection: network_cli
  tasks:

    - name: hostname
      ios_config:
        lines:
          - hostname R1
      become: yes
      become_method: enable

    - name: banner motd
      ios_banner:
        banner: motd
        text: "Do not access if not Authorized Personel"
      become: yes
      become_method: enable

    - name: service password-encryption
      ios_config:
        lines:
          - service password-encryption
      become: yes
      become_method: enable

    - name: line vty/con 0 password cisco
      ios_config:
        lines:
          - password cisco
          - login
        parents:
          - line vty 0 15
          - line console 0
      become: yes
      become_method: enable

    - name: en fa0/0
      ios_interfaces:
        config:
          - name: FastEthernet0/0
            description: Configured by Ansible Network
            enabled: True
      become: yes
      become_method: enable

    - name: save config
      ios_config:
        backup: true
      become: yes
      become_method: enable
